- name: test ansible
  hosts: "{{ host_list }}"
  gather_facts: false
  tasks:
    - ios_vlans:
        config:
          - name: "Vlan_{{vlan}}"
            vlan_id: "{{vlan}}"
            state: active
            shutdown: disabled
            remote_span: true
# - name: Change VLANs
#   hosts: "{{ host_list }}"
#   ios_vlans:
#     # config:
#     # - name: Vlan_10
#     #   vlan_id: 10
#     #   state: active
#     #   shutdown: disabled
#     #   remote_span: true